USE fsqa;

CREATE TABLE FSQA_SOUNDFILES (
  PROFILE_NAME          VARCHAR(30) PRIMARY KEY,
  WAV_FILE              VARCHAR(1024) NOT NULL,
  GOOD_SIMILARITY_PC    REAL,
  GOOD_MOS              REAL  
);

INSERT INTO FSQA_SOUNDFILES
(PROFILE_NAME, WAV_FILE, GOOD_SIMILARITY_PC, GOOD_MOS)
VALUES
('default', '/opt/sound/ITU-T_P_50_BRITISH_ENGLISH.wav', 94.60, 3.60),
('fsqa_scw01_30s', '/opt/sound/ITU-T_P_50_BRITISH_ENGLISH_30s.wav', 94.09, 3.59);

CREATE TABLE FSQA_TESTRESULTS (
  TEST_TIMESTAMP BIGINT NOT NULL,
  CALL_UUID      VARCHAR(40) NOT NULL,
  SRC_NAME       VARCHAR(256) NOT NULL,
  SIMILARITY_PC  REAL,
  MOS            REAL
);

CREATE INDEX FSQA_TESTRESULTS_I01 ON FSQA_TESTRESULTS (TEST_TIMESTAMP);
CREATE INDEX FSQA_TESTRESULTS_I02 ON FSQA_TESTRESULTS (SRC_NAME,TEST_TIMESTAMP);


CREATE USER 'fsqa_rw'@'localhost' IDENTIFIED BY 'EVai2xee';
GRANT SELECT ON FSQA_SOUNDFILES TO 'fsqa_rw'@'localhost';
GRANT SELECT,INSERT,DELETE ON FSQA_TESTRESULTS TO 'fsqa_rw'@'localhost';

CREATE USER 'fsqa_ro'@'localhost' IDENTIFIED BY 'Gie0ieNg';
GRANT SELECT ON FSQA_SOUNDFILES TO 'fsqa_ro'@'localhost';
GRANT SELECT ON FSQA_TESTRESULTS TO 'fsqa_ro'@'localhost';
